import { NextRequest, NextResponse } from 'next/server';

// Mock market data for initial development
// Will be replaced with database queries once Drizzle is connected
const MOCK_MARKETS = [
  {
    city: 'Mumbai',
    state: 'Maharashtra',
    tier: 1,
    latitude: 19.076,
    longitude: 72.8777,
    population: 20411000,
    healthIndex: 82,
    medianPricePerSqFt: 18500,
    priceChangeYoY: 7.2,
    priceChangeMoM: 0.8,
    activeListings: 45200,
    newLaunches30d: 340,
    unsoldInventory: 128000,
    monthsOfInventory: 28,
    reraProjects: 8450,
    avgAqi: 156,
    metroConnectivity: true,
    avgRentalYield: 2.8,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Delhi',
    state: 'Delhi',
    tier: 1,
    latitude: 28.6139,
    longitude: 77.209,
    population: 16787941,
    healthIndex: 75,
    medianPricePerSqFt: 12800,
    priceChangeYoY: 5.8,
    priceChangeMoM: 0.5,
    activeListings: 38500,
    newLaunches30d: 280,
    unsoldInventory: 95000,
    monthsOfInventory: 24,
    reraProjects: 3200,
    avgAqi: 210,
    metroConnectivity: true,
    avgRentalYield: 2.5,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Bangalore',
    state: 'Karnataka',
    tier: 1,
    latitude: 12.9716,
    longitude: 77.5946,
    population: 12326532,
    healthIndex: 88,
    medianPricePerSqFt: 9200,
    priceChangeYoY: 12.5,
    priceChangeMoM: 1.2,
    activeListings: 52000,
    newLaunches30d: 420,
    unsoldInventory: 78000,
    monthsOfInventory: 16,
    reraProjects: 6200,
    avgAqi: 82,
    metroConnectivity: true,
    avgRentalYield: 3.4,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Hyderabad',
    state: 'Telangana',
    tier: 1,
    latitude: 17.385,
    longitude: 78.4867,
    population: 10534418,
    healthIndex: 91,
    medianPricePerSqFt: 7800,
    priceChangeYoY: 15.3,
    priceChangeMoM: 1.5,
    activeListings: 34000,
    newLaunches30d: 380,
    unsoldInventory: 52000,
    monthsOfInventory: 12,
    reraProjects: 4800,
    avgAqi: 95,
    metroConnectivity: true,
    avgRentalYield: 3.8,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Chennai',
    state: 'Tamil Nadu',
    tier: 1,
    latitude: 13.0827,
    longitude: 80.2707,
    population: 10971108,
    healthIndex: 78,
    medianPricePerSqFt: 7200,
    priceChangeYoY: 6.8,
    priceChangeMoM: 0.6,
    activeListings: 28000,
    newLaunches30d: 250,
    unsoldInventory: 45000,
    monthsOfInventory: 18,
    reraProjects: 5100,
    avgAqi: 72,
    metroConnectivity: true,
    avgRentalYield: 3.2,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Pune',
    state: 'Maharashtra',
    tier: 1,
    latitude: 18.5204,
    longitude: 73.8567,
    population: 7764000,
    healthIndex: 85,
    medianPricePerSqFt: 7500,
    priceChangeYoY: 9.4,
    priceChangeMoM: 0.9,
    activeListings: 42000,
    newLaunches30d: 360,
    unsoldInventory: 62000,
    monthsOfInventory: 15,
    reraProjects: 7800,
    avgAqi: 88,
    metroConnectivity: true,
    avgRentalYield: 3.5,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Kolkata',
    state: 'West Bengal',
    tier: 1,
    latitude: 22.5726,
    longitude: 88.3639,
    population: 14850000,
    healthIndex: 68,
    medianPricePerSqFt: 5800,
    priceChangeYoY: 4.2,
    priceChangeMoM: 0.3,
    activeListings: 22000,
    newLaunches30d: 180,
    unsoldInventory: 48000,
    monthsOfInventory: 22,
    reraProjects: 2800,
    avgAqi: 145,
    metroConnectivity: true,
    avgRentalYield: 3.0,
    updatedAt: new Date().toISOString(),
  },
  {
    city: 'Ahmedabad',
    state: 'Gujarat',
    tier: 1,
    latitude: 23.0225,
    longitude: 72.5714,
    population: 8450000,
    healthIndex: 80,
    medianPricePerSqFt: 5200,
    priceChangeYoY: 8.1,
    priceChangeMoM: 0.7,
    activeListings: 26000,
    newLaunches30d: 220,
    unsoldInventory: 38000,
    monthsOfInventory: 14,
    reraProjects: 4200,
    avgAqi: 110,
    metroConnectivity: true,
    avgRentalYield: 3.1,
    updatedAt: new Date().toISOString(),
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const city = searchParams.get('city');
  const tier = searchParams.get('tier');

  let markets = MOCK_MARKETS;

  if (city) {
    markets = markets.filter((m) => m.city.toLowerCase() === city.toLowerCase());
  }

  if (tier) {
    markets = markets.filter((m) => m.tier === parseInt(tier, 10));
  }

  return NextResponse.json({
    data: markets,
    meta: {
      total: markets.length,
      page: 1,
      pageSize: 25,
    },
    updatedAt: new Date().toISOString(),
  });
}
